export const ERROR_USER_DOCUMENT_NOT_FOUND = "ERROR_USER_DOCUMENT_NOT_FOUND";
export const ERROR_USER_META_DOCUMENT_NOT_FOUND = "ERROR_USER_META_DOCUMENT_NOT_FOUND";
export const ERROR_CATEGORY_DOCUMENT_NOT_FOUND = "ERROR_CATEGORY_DOCUMENT_NOT_FOUND";
export const ERROR_POST_DOCUMENT_NOT_FOUND = "ERROR_POST_DOCUMENT_NOT_FOUND";
